import { useOutletContext, useActionData } from "@remix-run/react";
import type { User, Provider, UserIdentity } from "@supabase/supabase-js";
import { type FC, useEffect } from "react";
import { Form } from "@remix-run/react";
import { redirect } from "@remix-run/node";

import { getSupabaseAuth } from "~/utils/supabase";
import { SubmitButton } from "~/components/buttons";
import { HeadingBreak, ContentCard } from "~/components/cards";
import { PROVIDERS } from "~/types/providers";
import { ModelConfigurations } from "~/components/lists";
import type { UserModelConfig, ModelProvider } from "~/types/database";

export async function action({ request }: { request: Request }) {
    const formData = await request.formData();
    const provider = formData.get("provider");
    const connected = formData.get("connected") === "1";
    const { supabase, headers } = getSupabaseAuth(request);
    const url = new URL(request.url);
    const redirectUrl = `${url.origin}/api/auth-callback?next=/settings`;
    try {
        if (connected) {
            // Disconnect identity
            const { data } = await supabase.auth.getUserIdentities();
            if (!data?.identities) throw new Error("No identities found");
            const matchingIdentity = data.identities.find((identity: UserIdentity) => identity.provider === provider);
            if (!matchingIdentity) throw new Error("Identity not found");
            const { error } = await supabase.auth.unlinkIdentity(matchingIdentity);
            if (error) throw error;
            return Response.json({ status: 200 });
        } else {
            // Connect identity
            const { data, error } = await supabase.auth.linkIdentity({
                provider: provider as Provider,
                options: {
                    redirectTo: redirectUrl,
                },
            });
            if (error) throw error;
            return redirect(data.url, { headers });
        }
    } catch (error: unknown) {
        console.error(error);
        // Type guard for Error object
        if (error instanceof Error) {
            return Response.json({ error: error.message, status: 500 }, { status: 500 });
        }
        return Response.json({ error: "An unknown error occurred", status: 500 }, { status: 500 });
    }
}

export default function Settings() {
    const { modelConfigs, modelProviders } = useOutletContext<{ modelConfigs: UserModelConfig[], modelProviders: ModelProvider[] }>();

    // alert generated by action
    const actionData = useActionData<typeof action>();
    useEffect(() => {
        if (actionData?.error) {
            alert(`ERR - ${actionData.status}\n${actionData.error}`);
        }
    }, [actionData]);

    return (
        <div className="space-y-6">
            <ContentCard title="Model Configurations">
                <ModelConfigurations modelConfigs={modelConfigs} modelProviders={modelProviders} />
            </ContentCard>
            <ContentCard title="Accounts">
                <Accounts />
            </ContentCard>
        </div>
    );
}

// Displays the connected accounts and allows the user to connect or disconnect from them
function Accounts() {
    const { userData } = useOutletContext<{ userData: User }>();
    const connectedProviders = PROVIDERS.filter((provider) =>
        userData.identities?.some((identity) => identity.provider === provider.id)
    );

    const nonConnectedProviders = PROVIDERS.filter(
        (provider) => !userData.identities?.some((identity) => identity.provider === provider.id)
    );
    return (
        <>
            <HeadingBreak label="Connected Accounts" />
            <div className="space-y-2">
                {connectedProviders.map((provider) => (
                    <ProviderDetails
                        id={provider.id}
                        name={provider.name}
                        Icon={provider.icon}
                        connected={true}
                        key={provider.id}
                    />
                ))}
            </div>
            {nonConnectedProviders.length > 0 && (
                <>
                    <HeadingBreak label="Other Accounts" colour="red" />
                    <div className="space-y-2">
                        {nonConnectedProviders.map((provider) => (
                            <ProviderDetails
                                id={provider.id}
                                name={provider.name}
                                Icon={provider.icon}
                                connected={false}
                                key={provider.id}
                            />
                        ))}
                    </div>
                </>
            )}
        </>
    );
}

interface ProviderDetailsProps {
    id: string;
    name: string;
    Icon?: FC<{ className?: string }>;
    connected: boolean;
}
function ProviderDetails({ id, name, Icon, connected }: ProviderDetailsProps) {
    return (
        <div key={id} className="flex items-center justify-between py-2 px-4 bg-theme-surface-secondary rounded-lg">
            <div className="flex items-center space-x-3">
                {Icon && <Icon className="w-6 h-6" />}
                <span className="font-medium">{name}</span>
            </div>
            <Form method="post">
                <input type="hidden" name="provider" value={id} />
                <input type="hidden" name="connected" value={connected ? "1" : "0"} />
                {connected ? (
                    <SubmitButton label="Disconnect" className="bg-theme-error hover:bg-theme-error-hover" />
                ) : (
                    <SubmitButton label="Connect" className="bg-theme-success hover:bg-theme-success-hover" />
                )}
            </Form>
        </div>
    );
}
