import { useOutletContext, useActionData, useLoaderData, useFetcher } from "@remix-run/react";
import type { User, Provider, UserIdentity } from "@supabase/supabase-js";
import { type FC, useEffect, useState } from "react";
import { Form } from "@remix-run/react";
import { redirect } from "@remix-run/node";

import { getSupabaseAuth } from "~/utils/supabase";
import { SubmitButton } from "~/components/buttons";
import { HeadingBreak, ContentCard } from "~/components/cards";
import { PROVIDERS } from "~/types/providers";
import { ModelConfigForm, FormActionResponse } from "~/components/forms";
import { ActionButton } from "~/components/buttons";
import { useConfirmationOverlay } from "~/components/overlays";

export async function loader({ request }: { request: Request }) {
    const { supabase } = getSupabaseAuth(request);

    // Get the current user with getUser() for better security
    const { data: { user }, error: userError } = await supabase.auth.getUser();

    if (userError || !user) {
        console.error("Error fetching user:", userError);
        throw redirect("/login");
    }

    // Fetch user model configurations
    const { data: modelConfigs, error: configsError } = await supabase
        .from('user_model_configs')
        .select('*')
        .eq('owner_id', user.id);

    if (configsError) {
        console.error("Error fetching model configurations:", configsError);
    }

    // Fetch model providers
    const { data: modelProviders, error: providersError } = await supabase
        .from('model_providers')
        .select('id, name');

    if (providersError) {
        console.error("Error fetching model providers:", providersError);
    }

    return {
        modelConfigs: modelConfigs || [],
        modelProviders: modelProviders || []
    };
}

export async function action({ request }: { request: Request }) {
    const formData = await request.formData();
    const provider = formData.get("provider");
    const connected = formData.get("connected") === "1";
    const { supabase, headers } = getSupabaseAuth(request);
    try {
        if (connected) {
            // Disconnect identity
            const { data } = await supabase.auth.getUserIdentities();
            if (!data?.identities) throw new Error("No identities found");
            const matchingIdentity = data.identities.find((identity: UserIdentity) => identity.provider === provider);
            if (!matchingIdentity) throw new Error("Identity not found");
            const { error } = await supabase.auth.unlinkIdentity(matchingIdentity);
            if (error) throw error;
            return Response.json({ status: 200 });
        } else {
            // Connect identity
            const { data, error } = await supabase.auth.linkIdentity({
                provider: provider as Provider,
                options: {
                    redirectTo: `${process.env.APP_URL}/api/auth-callback?next=/settings`,
                },
            });
            if (error) throw error;
            return redirect(data.url, { headers });
        }
    } catch (error: unknown) {
        console.error(error);
        // Type guard for Error object
        if (error instanceof Error) {
            return Response.json({ error: error.message, status: 500 }, { status: 500 });
        }
        return Response.json({ error: "An unknown error occurred", status: 500 }, { status: 500 });
    }
}

export default function Settings() {
    // alert generated by action
    const actionData = useActionData<typeof action>();
    useEffect(() => {
        if (actionData?.error) {
            alert(`ERR - ${actionData.status}\n${actionData.error}`);
        }
    }, [actionData]);

    return (
        <div className="space-y-6">
            <ModelConfigurations />
            <Accounts />
        </div>
    );
}

// Displays the user's model configurations
function ModelConfigurations() {
    const { modelConfigs, modelProviders } = useLoaderData<typeof loader>();
    const [formHidden, setFormHidden] = useState(true);
    const [initialValues, setInitialValues] = useState<any>(null);
    const deleteFetcher = useFetcher<FormActionResponse>();

    // Helper function to reset form state
    const hideForm = () => {
        setInitialValues(null);
        setFormHidden(true);
    };

    // Execute delete when confirmed
    const executeDelete = () => {
        if (!deleteConfirmation.confirmationData) return;

        deleteFetcher.submit(
            { id: deleteConfirmation.confirmationData },
            { method: "post", action: "/api/delete-model-config" }
        );
    };

    // Custom overlay hook
    const deleteConfirmation = useConfirmationOverlay({
        heading: "Confirm Delete",
        subheading: "Are you sure you want to delete this model configuration? This action cannot be undone.",
        continueButtonLabel: "Delete",
        onContinue: executeDelete,
        isLoading: deleteFetcher.state === "submitting",
        continueButtonClassName: "bg-theme-error hover:bg-theme-error-hover"
    });

    // Clear confirmation when delete is complete
    useEffect(() => {
        if (deleteFetcher.data?.success) {
            deleteConfirmation.hideConfirmation();
        } else if (deleteFetcher.data?.error) {
            alert(`Error: ${deleteFetcher.data.error}`);
            deleteConfirmation.hideConfirmation();
        }
    }, [deleteFetcher.data]);

    return (
        <ContentCard title="Model Configurations">
            {modelConfigs.length > 0 ? (
                <div className="space-y-4">
                    <HeadingBreak label="Your Model Configurations" />
                    <div className="space-y-2">
                        {modelConfigs.map((config) => (
                            <div key={config.id} className="flex items-center justify-between py-3 px-4 bg-theme-surface-secondary rounded-lg">
                                <div>
                                    <h3 className="font-medium text-lg">{config.name || 'Unnamed Configuration'}</h3>
                                    <p className="text-sm text-gray-300">
                                        {modelProviders.find(p => p.id === config.model_provider_id)?.name || 'No model specified'}
                                    </p>
                                </div>
                                <div className="flex space-x-2">
                                    <ActionButton
                                        label="Edit"
                                        className="px-3 py-1 text-sm"
                                        onClick={() => {
                                            setInitialValues(config);
                                            setFormHidden(false);
                                        }}
                                    />
                                    <ActionButton
                                        label="Delete"
                                        className="px-3 py-1 text-sm bg-theme-error hover:bg-theme-error-hover"
                                        onClick={() => deleteConfirmation.showConfirmation(config.id)}
                                    />
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            ) : (
                <div className="py-6 text-center">
                    <p className="text-gray-400">No model configurations found</p>
                </div>
            )}

            {/* Edit form */}
            {formHidden ? (
                <div className="text-center">
                    <ActionButton label="Create New Configuration" onClick={() => setFormHidden(false)} />
                </div>
            ) : (
                <div>
                    <ModelConfigForm
                        modelProviders={modelProviders}
                        initialValues={initialValues}
                        onCancel={hideForm}
                        onSuccess={hideForm}
                    />
                </div>
            )}
            {deleteConfirmation.ConfirmationOverlayComponent}
        </ContentCard>
    );
}

// Displays the connected accounts and allows the user to connect or disconnect from them
function Accounts() {
    const userData = useOutletContext<User>();
    const connectedProviders = PROVIDERS.filter((provider) =>
        userData.identities?.some((identity) => identity.provider === provider.id)
    );

    const nonConnectedProviders = PROVIDERS.filter(
        (provider) => !userData.identities?.some((identity) => identity.provider === provider.id)
    );
    return (
        <ContentCard title="Accounts">
            <HeadingBreak label="Connected Accounts" />
            <div className="space-y-2">
                {connectedProviders.map((provider) => (
                    <ProviderDetails
                        id={provider.id}
                        name={provider.name}
                        Icon={provider.icon}
                        connected={true}
                        key={provider.id}
                    />
                ))}
            </div>
            {nonConnectedProviders.length > 0 && (
                <>
                    <HeadingBreak label="Other Accounts" colour="red" />
                    <div className="space-y-2">
                        {nonConnectedProviders.map((provider) => (
                            <ProviderDetails
                                id={provider.id}
                                name={provider.name}
                                Icon={provider.icon}
                                connected={false}
                                key={provider.id}
                            />
                        ))}
                    </div>
                </>
            )}
        </ContentCard>
    );
}

interface ProviderDetailsProps {
    id: string;
    name: string;
    Icon?: FC<{ className?: string }>;
    connected: boolean;
}
function ProviderDetails({ id, name, Icon, connected }: ProviderDetailsProps) {
    return (
        <div key={id} className="flex items-center justify-between py-2 px-4 bg-theme-surface-secondary rounded-lg">
            <div className="flex items-center space-x-3">
                {Icon && <Icon className="w-6 h-6" />}
                <span className="font-medium">{name}</span>
            </div>
            <Form method="post">
                <input type="hidden" name="provider" value={id} />
                <input type="hidden" name="connected" value={connected ? "1" : "0"} />
                {connected ? (
                    <SubmitButton label="Disconnect" className="bg-theme-error hover:bg-theme-error-hover" />
                ) : (
                    <SubmitButton label="Connect" className="bg-theme-success hover:bg-theme-success-hover" />
                )}
            </Form>
        </div>
    );
}
